# Generated by Django 5.2.1 on 2025-05-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0009_alter_format_unique_together'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_formats',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='cameras.format'),
        ),
    ]
