# Generated by Django 5.2.1 on 2025-08-17 19:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formats', '0002_format_format_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='format',
            name='anamorphic_squeeze',
            field=models.FloatField(default=1.0, help_text='Lens anamorphic factor (2.0 is the most common but can me 1.8, 1.33, etc)'),
        ),
        migrations.AlterField(
            model_name='format',
            name='filmback_height_3de',
            field=models.FloatField(blank=True, help_text='3DE filmback height in mm', null=True),
        ),
        migrations.AlterField(
            model_name='format',
            name='filmback_width_3de',
            field=models.FloatField(blank=True, help_text='3DE filmback width in mm', null=True),
        ),
        migrations.AlterField(
            model_name='format',
            name='pixel_aspect',
            field=models.FloatField(default=1.0, help_text='Pixel aspect', validators=[django.core.validators.MinValueValidator(0.1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='format',
            name='sensor_height',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='format',
            name='sensor_width',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
