# Generated by Django 5.2.1 on 2025-05-17 20:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CameraManufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('sensor_type', models.CharField(max_length=100)),
                ('max_filmback_width', models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum filmback size in mm', max_digits=5)),
                ('max_filmback_height', models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum filmback size in mm', max_digits=5)),
                ('max_image_width', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_image_height', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_frame_rate', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_frame_rate', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='cameras.cameramanufacturer')),
            ],
            options={
                'unique_together': {('manufacturer', 'model')},
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_format', models.CharField(max_length=5)),
                ('image_aspect', models.CharField(max_length=10)),
                ('format_name', models.CharField(blank=True, max_length=100)),
                ('sensor_width', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('sensor_height', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('image_width', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('image_height', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('is_downsampled', models.BooleanField(default=False)),
                ('codec', models.CharField(blank=True, max_length=20)),
                ('anamorphic', models.BooleanField(default=False)),
                ('pixel_aspect', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formats', to='cameras.camera')),
            ],
            options={
                'unique_together': {('camera', 'image_format', 'image_aspect', 'anamorphic', 'codec')},
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('format_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='cameras.format')),
            ],
        ),
    ]
