# Generated by Django 5.2.1 on 2025-06-08 17:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('makes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('sensor_type', models.CharField(max_length=100)),
                ('max_filmback_width', models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum filmback size in mm', max_digits=5)),
                ('max_filmback_height', models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum filmback size in mm', max_digits=5)),
                ('max_image_width', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_image_height', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('min_frame_rate', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_frame_rate', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('discontinued', models.BooleanField(default=False, help_text='Was this model discontinued by the make?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='makes.make')),
            ],
            options={
                'unique_together': {('make', 'model')},
            },
        ),
    ]
