# Generated by Django 5.2.1 on 2025-06-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='camera_images/'),
        ),
    ]
