# Generated by Django 5.2.1 on 2025-05-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='format',
            name='anamorphic_squeeze',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Lens anamorphic factor (2.0 is the most common but can me 1.8, 1.33, etc)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='format',
            name='pixel_aspect',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Pixel aspect', max_digits=4),
        ),
    ]
