# Generated by Django 5.2.1 on 2025-05-14 19:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('sensor_type', models.CharField(max_length=100)),
                ('max_filmback_size', models.DecimalField(decimal_places=2, help_text='Maximum filmback size in mm', max_digits=5)),
                ('min_frame_rate', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_frame_rate', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='cameras.cameramanufacturer')),
            ],
            options={
                'unique_together': {('manufacturer', 'model')},
            },
        ),
    ]
