# Generated by Django 5.2.1 on 2025-05-18 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='format_record',
        ),
        migrations.AddField(
            model_name='format',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formats', to='cameras.source'),
        ),
    ]
