# Generated by Django 5.2.1 on 2025-05-14 20:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_camera'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_format', models.CharField(max_length=5)),
                ('image_aspect', models.CharField(max_length=10)),
                ('image_width', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('image_height', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('sensor_width', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('sensor_height', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('anamorphic', models.BooleanField(default=False)),
                ('pixel_aspect', models.DecimalField(decimal_places=2, default=1.0, max_digits=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formats', to='cameras.camera')),
            ],
            options={
                'unique_together': {('camera', 'image_format', 'image_aspect', 'anamorphic')},
            },
        ),
    ]
