# Generated by Django 5.2.1 on 2025-05-19 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_alter_format_anamorphic_squeeze_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='manufacturer_notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='format',
            name='raw_recording_available',
            field=models.BooleanField(default=True, help_text='Is the raw, unprocessed format available for recording?'),
        ),
    ]
