# Generated by Django 5.2.1 on 2025-06-22 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_camera_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='sensor_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
