# Generated by Django 5.2.1 on 2025-05-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_format_manufacturer_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='file_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
