# Generated by Django 5.2.1 on 2025-05-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='format_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
