# Generated by Django 5.2.1 on 2025-05-19 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0004_source_file_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='format',
            unique_together={('camera', 'image_format', 'image_aspect', 'format_name', 'is_anamorphic', 'codec', 'is_downsampled')},
        ),
    ]
