# Generated by Django 5.2.1 on 2025-05-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0005_alter_format_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='format',
            name='is_upscaled',
            field=models.BooleanField(default=False),
        ),
    ]
