# Generated by Django 5.2.1 on 2025-05-19 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0006_format_is_upscaled'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='notes',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
