# Generated by Django 5.2.1 on 2025-05-20 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0007_camera_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='discontinued',
            field=models.BooleanField(default=False, help_text='Was this model discontinued by the manufacturer?'),
        ),
    ]
