# Generated by Django 5.2.1 on 2025-05-21 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0008_camera_discontinued'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='format',
            unique_together={('camera', 'image_format', 'image_aspect', 'format_name', 'is_anamorphic', 'codec', 'is_downsampled', 'pixel_aspect')},
        ),
    ]
