# Generated by Django 5.2.1 on 2025-05-28 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0009_alter_format_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CameraManufacturer',
            new_name='Make',
        ),
    ]
