# Generated by Django 5.2.1 on 2025-05-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0009_alter_format_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('poster_path', models.CharField(blank=True, max_length=200)),
                ('release_date', models.DateField(blank=True)),
                ('adult', models.BooleanField(default=False)),
                ('tmdb_id', models.IntegerField(blank=True)),
                ('tmdb_original_name', models.CharField(blank=True, max_length=100)),
                ('cameras', models.ManyToManyField(blank=True, related_name='used_in_projects', to='cameras.camera')),
                ('formats', models.ManyToManyField(blank=True, related_name='used_in_projects', to='cameras.format')),
            ],
        ),
    ]
