# Generated by Django 5.2.1 on 2025-06-08 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
        ('formats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True)),
                ('project_type', models.CharField(choices=[('feature', 'Feature'), ('episodic', 'Episodic')], default='feature', max_length=10)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('poster_path', models.CharField(blank=True, max_length=200)),
                ('release_date', models.DateField(blank=True)),
                ('adult', models.BooleanField(default=False)),
                ('tmdb_id', models.IntegerField(blank=True, null=True)),
                ('tmdb_original_name', models.CharField(blank=True, max_length=100)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('rating', models.JSONField(blank=True, default=list)),
                ('cameras', models.ManyToManyField(blank=True, related_name='used_in_projects', to='cameras.camera')),
                ('formats', models.ManyToManyField(blank=True, related_name='used_in_projects', to='formats.format')),
            ],
        ),
    ]
