# Generated by Django 5.2.1 on 2025-05-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('feature', 'Feature'), ('episodic', 'Episodic')], default='feature', max_length=10),
        ),
    ]
