# Generated by Django 5.2.1 on 2025-05-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
