# Generated by Django 5.2.1 on 2025-06-16 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectformat_vote_delete_projectformatvote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectformat',
            old_name='created_by',
            new_name='added_by',
        ),
    ]
