# Generated by Django 5.2.1 on 2025-05-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_tmdb_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
