# Generated by Django 5.2.1 on 2025-05-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rating',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
