# Generated by Django 5.2.1 on 2025-06-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('makes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='make',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='make_logos'),
        ),
    ]
