from cameras.models import Make, Camera, Format, Source
from django.db import transaction, connection
from loguru import logger


@transaction.atomic
def clear_database():
    # Format.objects.delete() returns a tuple (count_deleted, dict_with_details)
    formats_deleted = Format.objects.all().delete()[0]
    sources_deleted = Source.objects.all().delete()[0]
    cameras_deleted = Camera.objects.all().delete()[0]
    makes_deleted = Make.objects.all().delete()[0]

    with connection.cursor() as cursor:
        cursor.execute("ALTER SEQUENCE cameras_format_id_seq RESTART WITH 1;")
        cursor.execute("ALTER SEQUENCE cameras_source_id_seq RESTART WITH 1;")
        cursor.execute("ALTER SEQUENCE cameras_camera_id_seq RESTART WITH 1;")
        cursor.execute("ALTER SEQUENCE cameras_make_id_seq RESTART WITH 1;")

    logger.info(f"Deleted {makes_deleted} makes")
    logger.info(f"Deleted {cameras_deleted} cameras")
    logger.info(f"Deleted {sources_deleted} sources")
    logger.info(f"Deleted {formats_deleted} formats")

    return {
        "makes": makes_deleted,
        "cameras": cameras_deleted,
        "sources": sources_deleted,
        "formats": formats_deleted,
    }


@transaction.atomic
def seed_makes():
    makes = [
        {"name": "ARRI", "website": "https://www.arri.com/en"},
        {"name": "RED", "website": "https://www.red.com"},
    ]

    created_makes = {}
    for m in makes:
        make, new = Make.objects.get_or_create(**m)
        created_makes[m["name"]] = make
        logger.info(f"{'Created' if new else 'Found'} make: {make.name}")

    return created_makes


@transaction.atomic
def seed_cameras(makes):
    cameras = [
        {
            "make": makes.get("ARRI") or Make.objects.get("ARRI"),
            "model": "Alexa 35",
            "sensor_type": "Super 35 format ARRI ALEV 4 CMOS sensor with Bayer pattern color filter array",
            "max_filmback_width": 27.99,
            "max_filmback_height": 19.22,
            "max_image_width": 4608,
            "max_image_height": 3164,
            "min_frame_rate": 0.75,
            "max_frame_rate": 120,
        },
        {
            "make": makes.get("ARRI") or Make.objects.get("ARRI"),
            "model": "Alexa Mini LF",
            "sensor_type": "Large Format ARRI ALEV III (A2X) CMOS sensor with Bayer pattern color filter array",
            "max_filmback_width": 36.70,
            "max_filmback_height": 25.54,
            "max_image_width": 4448,
            "max_image_height": 3096,
            "min_frame_rate": 0.75,
            "max_frame_rate": 90,
        },
        {
            "make": makes.get("ARRI") or Make.objects.get("ARRI"),
            "model": "Alexa LF",
            "sensor_type": "Large Format ARRI ALEV III (A2X) CMOS sensor with Bayer pattern color filter array",
            "max_filmback_width": 36.70,
            "max_filmback_height": 25.54,
            "max_image_width": 4448,
            "max_image_height": 3096,
            "min_frame_rate": 0.75,
            "max_frame_rate": 150,
        },
        {
            "make": makes.get("ARRI") or Make.objects.get("ARRI"),
            "model": "Alexa Amira",
            "sensor_type": "Super 35 format ARRI ALEV III CMOS sensor with Bayer pattern color filter array",
            "max_filmback_width": 26.40,
            "max_filmback_height": 14.85,
            "max_image_width": 3200,
            "max_image_height": 1800,
            "min_frame_rate": 0.75,
            "max_frame_rate": 200,
        },
        {
            "make": makes.get("ARRI") or Make.objects.get("ARRI"),
            "model": "Alexa SXT W",
            "sensor_type": "Super 35 format ARRI ALEV III CMOS sensor with Bayer pattern color filter array",
            "max_filmback_width": 28.25,
            "max_filmback_height": 18.17,
            "max_image_width": 3424,
            "max_image_height": 2202,
            "min_frame_rate": 0.75,
            "max_frame_rate": 120,
            "notes": "This model also covers the SXT, SXT Plus and SXT Studio",
        },
        {
            "make": makes.get("ARRI") or Make.objects.get("ARRI"),
            "model": "Alexa Mini",
            "sensor_type": "Super 35 format ARRI ALEV III CMOS sensor with Bayer pattern color filter array",
            "max_filmback_width": 28.25,
            "max_filmback_height": 18.17,
            "max_image_width": 3424,
            "max_image_height": 2202,
            "min_frame_rate": 0.75,
            "max_frame_rate": 120,
            "discontinued": True,
        },
        {
            "make": makes.get("RED") or Make.objects.get("RED"),
            "model": "KOMODO",
            "sensor_type": "KOMODO® 19.9 MP Super 35mm Global Shutter CMOS",
            "max_filmback_width": 27.03,
            "max_filmback_height": 14.26,
            "max_image_width": 6144,
            "max_image_height": 3240,
            "min_frame_rate": 24,
            "max_frame_rate": 120,
        },
        {
            "make": makes.get("RED") or Make.objects.get("RED"),
            "model": "KOMODO-X",
            "sensor_type": "KOMODO-X™ 19.9MP Super 35mm Global Shutter CMOS",
            "max_filmback_width": 27.03,
            "max_filmback_height": 14.26,
            "max_image_width": 6144,
            "max_image_height": 3240,
            "min_frame_rate": 24,
            "max_frame_rate": 240,
        },
    ]

    created_cameras = {}
    for cam in cameras:
        camera, new = Camera.objects.get_or_create(**cam)
        created_cameras[cam["model"]] = camera
        logger.info(f"{'Created' if new else 'Found'} camera: {camera.model}")

    return created_cameras


@transaction.atomic
def seed_sources():
    sources = [
        {
            "name": "Alexa 35 User Manual",
            "url": "https://www.arri.com/resource/blob/389818/03a1421ba039d246cd4c895c2f791f79/alexa-35-user-manual-sup-4-0-0-data.pdf",
            "file_name": "ARRI ALEXA 35 SUP 4.0.0 - User Manual.pdf",
        },
        {
            "name": "Alexa Mini User Manual",
            "url": "https://www.arri.com/resource/blob/347174/6b8fd84caac842b3c9292c910fcee693/alexa-mini-lf-sup-7-3-user-manual-data.pdf",
            "file_name": "ALEXA Mini LF SUP 7.3 - User Manual.pdf",
        },
        {
            "name": "Alexa LF Webpage",
            "url": "https://www.arri.com/en/camera-systems/cameras/alexa-lf",
            "file_name": "ALEXA LF _ Camera Systems _ ARRI.pdf",
            "note": "Printing the webpage reveals the full technical data. Or you can expand the technical data section manually",
        },
        {
            "name": "Alexa Amira Webpage",
            "url": "https://www.arri.com/en/camera-systems/cameras/amira",
            "file_name": "ALEXA AMIRA _ Camera Systems _ ARRI.pdf",
            "note": "Printing the webpage reveals the full technical data. Or you can expand the technical data section manually",
        },
        {
            "name": "Alexa SXT W Webpage",
            "url": "https://www.arri.com/en/camera-systems/cameras/legacy-camera-systems/alexa-sxt-w",
            "file_name": "ALEXA SXT W _ Camera Systems _ ARRI.pdf",
            "note": "Printing the webpage reveals the full technical data. Or you can expand the technical data section manually",
        },
        {
            "name": "Alexa Mini Recoding Areas Document",
            "url": "https://www.arri.com/resource/blob/178064/d84031615b6bf09446aeb7972066b129/alexa-mini-recording-areas-surround-views-and-framelines-sup-4-0-data.pdf",
            "file_name": "ALEXAMini_RecordingAreaSurroundViewsandFramelines_SUP_4.0_v1.1.pdf",
        },
        {
            "name": "KOMODO Operation Guide",
            "url": "https://www.red.com/download/komodo-operation-guide",
            "file_name": "955-0190_V1.7 Rev-B RED PS, KOMODO Operation Guide (1).pdf",
        },
        {
            "name": "KOMODO-X Operation Guide",
            "url": "https://www.red.com/downloads/komodo-x",
            "file_name": "955-0218_V2.0 Rev-A RED PS, KOMODO-X Operation Guide.pdf",
        },
    ]

    created_sources = {}
    for s in sources:
        source, new = Source.objects.get_or_create(**s)
        created_sources[s["name"]] = source
        logger.info(f"{'Created' if new else 'Found'} source`: {source.name}")

    return created_sources


@transaction.atomic
def seed_formats(cameras, sources):
    formats = [
        {
            "camera": cameras.get("Alexa 35") or Camera.objects.get("Alexa 35"),
            "image_format": "4.6K",
            "image_aspect": "3:2",
            "format_name": "Open Gate",
            "sensor_width": 28.0,
            "sensor_height": 19.2,
            "image_width": 4608,
            "image_height": 3164,
            "codec": "ARRIRAW",
            "source": sources.get("Alexa 35 User Manual"),
            "make_notes": "4.6K 3:2 Open Gate provides maximum image quality, resolution, and flexibility in post for many spherical and anamorphic lenses in an image area slightly larger than traditional Super 35 film specifications.",
        },
        {
            "camera": cameras.get("Alexa 35") or Camera.objects.get("Alexa 35"),
            "image_format": "4.6K",
            "image_aspect": "3:2",
            "format_name": "Open Gate",
            "sensor_width": 28.0,
            "sensor_height": 19.2,
            "image_width": 4608,
            "image_height": 3164,
            "codec": "ProRes",
            "source": sources.get("Alexa 35 User Manual"),
            "make_notes": "4.6K 3:2 Open Gate provides maximum image quality, resolution, and flexibility in post for many spherical and anamorphic lenses in an image area slightly larger than traditional Super 35 film specifications.",
        },
        {
            "camera": cameras.get("Alexa 35") or Camera.objects.get("Alexa 35"),
            "image_format": "4.6K",
            "image_aspect": "16:9",
            "sensor_width": 28.0,
            "sensor_height": 15.7,
            "image_width": 4608,
            "image_height": 2592,
            "codec": "ARRIRAW",
            "source": sources.get("Alexa 35 User Manual"),
            "make_notes": "Full sensor width recording in a 16:9 format that suits many spherical Super 35 and all large format lenses, with room for flexibility in post. Lower data rate than 4.6K 3.2 Open Gate.",
        },
        {
            "camera": cameras.get("Alexa 35") or Camera.objects.get("Alexa 35"),
            "image_format": "4K",
            "image_aspect": "16:9",
            "sensor_width": 28.0,
            "sensor_height": 15.7,
            "image_width": 4096,
            "image_height": 2304,
            "is_downsampled": True,
            "codec": "ProRes",
            "source": sources.get("Alexa 35 User Manual"),
            "notes": "Downsampled from 4.6K 16:9",
        },
        {
            "camera": cameras.get("Alexa 35") or Camera.objects.get("Alexa 35"),
            "image_format": "4K",
            "image_aspect": "16:9",
            "sensor_width": 24.9,
            "sensor_height": 14,
            "image_width": 4096,
            "image_height": 2304,
            "codec": "ARRIRAW",
            "source": sources.get("Alexa 35 User Manual"),
            "make_notes": "4K 16:9 mimics the traditional spherical Super 35 film format for maximum lens compatibility. Multiple in-camera downsampling options provide lower data rates.",
        },
        {
            "camera": cameras.get("Alexa 35") or Camera.objects.get("Alexa 35"),
            "image_format": "4K",
            "image_aspect": "16:9",
            "sensor_width": 24.9,
            "sensor_height": 14,
            "image_width": 4096,
            "image_height": 2304,
            "codec": "ProRes",
            "source": sources.get("Alexa 35 User Manual"),
            "make_notes": "4K 16:9 mimics the traditional spherical Super 35 film format for maximum lens compatibility. Multiple in-camera downsampling options provide lower data rates.",
        },
        {
            "camera": cameras.get("Alexa 35") or Camera.objects.get("Alexa 35"),
            "image_format": "UHD",
            "sensor_width": 24.9,
            "sensor_height": 14,
            "image_width": 3840,
            "image_height": 2160,
            "codec": "ProRes",
            "is_downsampled": True,
            "source": sources.get("Alexa 35 User Manual"),
            "notes": "Downsampled from 4K 16:9",
        },
        {
            "camera": cameras.get("Alexa 35") or Camera.objects.get("Alexa 35"),
            "image_format": "2K",
            "sensor_width": 24.9,
            "sensor_height": 14,
            "image_width": 2048,
            "image_height": 1152,
            "codec": "ProRes",
            "is_downsampled": True,
            "source": sources.get("Alexa 35 User Manual"),
            "notes": "Downsampled from 4K 16:9",
        },
        {
            "camera": cameras.get("Alexa 35") or Camera.objects.get("Alexa 35"),
            "image_format": "HD",
            "sensor_width": 24.9,
            "sensor_height": 14,
            "image_width": 2048,
            "image_height": 1152,
            "codec": "ProRes",
            "is_downsampled": True,
            "source": sources.get("Alexa 35 User Manual"),
            "notes": "Downsampled from 4K 16:9",
        },
        {
            "camera": cameras.get("Alexa 35") or Camera.objects.get("Alexa 35"),
            "image_format": "4K",
            "image_aspect": "2:1",
            "sensor_width": 24.9,
            "sensor_height": 12.4,
            "image_width": 4096,
            "image_height": 2048,
            "codec": "ARRIRAW",
            "source": sources.get("Alexa 35 User Manual"),
            "notes": "Downsampled from 4K 16:9",
            "make_notes": "4K 2:1 was designed for shooting with all spherical Super 35 and large format lenses for a target deliverable of 2:1, fulfilling 4K mandates.",
        },
        {
            "camera": cameras.get("Alexa 35") or Camera.objects.get("Alexa 35"),
            "image_format": "4K",
            "image_aspect": "2:1",
            "sensor_width": 24.9,
            "sensor_height": 12.4,
            "image_width": 4096,
            "image_height": 2048,
            "codec": "ProRes",
            "source": sources.get("Alexa 35 User Manual"),
            "make_notes": "4K 2:1 was designed for shooting with all spherical Super 35 and large format lenses for a target deliverable of 2:1, fulfilling 4K mandates.",
        },
        {
            "camera": cameras.get("Alexa 35") or Camera.objects.get("Alexa 35"),
            "image_format": "3.8K",
            "image_aspect": "16:9",
            "sensor_width": 23.3,
            "sensor_height": 13.1,
            "image_width": 3840,
            "image_height": 2160,
            "codec": "ARRIRAW",
            "source": sources.get("Alexa 35 User Manual"),
            "make_notes": "For projects using spherical lenses for a 16:9 UHD deliverable. Smaller sensor area than sensor mode `4.6K 16:9` ennsures that most S35 format lenses cover. Lower data rate and higher fps than sensor modes ‘4.6K 3:2 Open Gate’ and ‘4.6K 16:9’.",
        },
        {
            "camera": cameras.get("Alexa 35") or Camera.objects.get("Alexa 35"),
            "image_format": "3.8K",
            "image_aspect": "16:9",
            "sensor_width": 23.3,
            "sensor_height": 13.1,
            "image_width": 3840,
            "image_height": 2160,
            "codec": "ProRes",
            "source": sources.get("Alexa 35 User Manual"),
            "make_notes": "For projects using spherical lenses for a 16:9 UHD deliverable. Smaller sensor area than sensor mode `4.6K 16:9` ennsures that most S35 format lenses cover. Lower data rate and higher fps than sensor modes ‘4.6K 3:2 Open Gate’ and ‘4.6K 16:9’.",
        },
        {
            "camera": cameras.get("Alexa 35") or Camera.objects.get("Alexa 35"),
            "image_format": "3.3K",
            "image_aspect": "6:5",
            "sensor_width": 20.2,
            "sensor_height": 16.9,
            "image_width": 3328,
            "image_height": 2790,
            "codec": "ARRIRAW",
            "is_anamorphic": True,
            "pixel_aspect": 2.0,
            "source": sources.get("Alexa 35 User Manual"),
            "make_notes": "For projects using 2x anamorphic Super 35 lenses for a target deliverable of 2.39:1. Negates necessity of cropping 4:3 footage and fulfills 4K mandates.",
        },
        {
            "camera": cameras.get("Alexa 35") or Camera.objects.get("Alexa 35"),
            "image_format": "3.3K",
            "image_aspect": "6:5",
            "sensor_width": 20.2,
            "sensor_height": 16.9,
            "image_width": 3328,
            "image_height": 2790,
            "codec": "ProRes",
            "is_anamorphic": True,
            "pixel_aspect": 2.0,
            "source": sources.get("Alexa 35 User Manual"),
            "make_notes": "For projects using 2x anamorphic Super 35 lenses for a target deliverable of 2.39:1. Negates necessity of cropping 4:3 footage and fulfills 4K mandates.",
        },
        {
            "camera": cameras.get("Alexa 35") or Camera.objects.get("Alexa 35"),
            "image_format": "4K",
            "image_aspect": "2.39:1",
            "format_name": "Ana. 2X",
            "sensor_width": 20.2,
            "sensor_height": 16.9,
            "image_width": 4096,
            "image_height": 1716,
            "codec": "ProRes",
            "is_anamorphic": True,
            "is_desqueezed": True,
            "pixel_aspect": 2.0,
            "source": sources.get("Alexa 35 User Manual"),
            "notes": "Dezqueezed from 3.3K 6:5",
            "make_notes": "For projects using 2x anamorphic Super 35 lenses for a target deliverable of 2.39:1. Negates necessity of cropping 4:3 footage and fulfills 4K mandates.",
        },
        {
            "camera": cameras.get("Alexa 35") or Camera.objects.get("Alexa 35"),
            "image_format": "3K",
            "image_aspect": "1:1",
            "sensor_width": 18.7,
            "sensor_height": 18.7,
            "image_width": 3072,
            "image_height": 3072,
            "codec": "ARRIRAW",
            "is_anamorphic": True,
            "pixel_aspect": 2.0,
            "source": sources.get("Alexa 35 User Manual"),
            "make_notes": "3K 1:1 was designed for shooting with 2x anamorphic lenses for a target deliverable of 2:1, fulfilling 4K mandates.",
        },
        {
            "camera": cameras.get("Alexa 35") or Camera.objects.get("Alexa 35"),
            "image_format": "3K",
            "image_aspect": "1:1",
            "sensor_width": 18.7,
            "sensor_height": 18.7,
            "image_width": 3072,
            "image_height": 3072,
            "codec": "ProRes",
            "is_anamorphic": True,
            "pixel_aspect": 2.0,
            "make_notes": "3K 1:1 was designed for shooting with 2x anamorphic lenses for a target deliverable of 2:1, fulfilling 4K mandates.",
            "source": sources.get("Alexa 35 User Manual"),
        },
        {
            "camera": cameras.get("Alexa 35") or Camera.objects.get("Alexa 35"),
            "image_format": "3.8K",
            "image_aspect": "2:1",
            "format_name": "Ana. 2X",
            "sensor_width": 18.7,
            "sensor_height": 18.7,
            "image_width": 3840,
            "image_height": 1920,
            "codec": "ProRes",
            "is_anamorphic": True,
            "is_desqueezed": True,
            "pixel_aspect": 2.0,
            "source": sources.get("Alexa 35 User Manual"),
            "notes": "Dezqueezed from 3K 1:1",
            "make_notes": "3K 1:1 was designed for shooting with 2x anamorphic lenses for a target deliverable of 2:1, fulfilling 4K mandates.",
        },
        {
            "camera": cameras.get("Alexa 35") or Camera.objects.get("Alexa 35"),
            "image_format": "2.7K",
            "image_aspect": "8:9",
            "sensor_width": 16.7,
            "sensor_height": 18.8,
            "image_width": 2743,
            "image_height": 3086,
            "codec": "ARRIRAW",
            "is_anamorphic": True,
            "pixel_aspect": 2.0,
            "source": sources.get("Alexa 35 User Manual"),
            "make_notes": "For projects shooting with 2x anamorphic lenses for a target deliverable of 16:9, fulfilling 4K mandates. Desqueeze applied in-camera.",
            "raw_recording_available": False,  # This is a rare case where the ARRI does not keep the raw data
        },
        {
            "camera": cameras.get("Alexa 35") or Camera.objects.get("Alexa 35"),
            "image_format": "UHD",
            "image_aspect": "16:9",
            "format_name": "Ana. 2X",
            "sensor_width": 16.7,
            "sensor_height": 18.8,
            "image_width": 3840,
            "image_height": 2160,
            "codec": "ProRes",
            "is_anamorphic": True,
            "is_desqueezed": True,
            "pixel_aspect": 2.0,
            "source": sources.get("Alexa 35 User Manual"),
            "notes": "Dezqueezed from 2.7K 8:9 | This is a rare case where the raw data is not kept, all processing happens in-camera",
            "make_notes": "For projects shooting with 2x anamorphic lenses for a target deliverable of 16:9, fulfilling 4K mandates. Desqueeze applied in-camera.",
            "raw_recording_available": False,  # This is a rare case where the ARRI does not keep the raw data
        },
        {
            "camera": cameras.get("Alexa 35") or Camera.objects.get("Alexa 35"),
            "image_format": "2K",
            "image_aspect": "16:9",
            "format_name": "S16",
            "sensor_width": 12.4,
            "sensor_height": 7.0,
            "image_width": 2048,
            "image_height": 1152,
            "codec": "ProRes",
            "source": sources.get("Alexa 35 User Manual"),
            "make_notes": "2K 16:9 S16 mimics the traditional Super 16 format for use with Super 16 lenses or as an in-camera center crop.",
        },
        {
            "camera": cameras.get("Alexa Mini LF")
            or Camera.objects.get("Alexa Mini LF"),
            "image_format": "4.5K LF",
            "image_aspect": "3:2",
            "format_name": "Open Gate",
            "sensor_width": 36.70,
            "sensor_height": 25.54,
            "image_width": 4448,
            "image_height": 3096,
            "codec": "ARRIRAW",
            "source": sources.get("Alexa Mini User Manual"),
        },
        {
            "camera": cameras.get("Alexa Mini LF")
            or Camera.objects.get("Alexa Mini LF"),
            "image_format": "4.5K LF",
            "image_aspect": "2.39:1",
            "format_name": "Open Gate",
            "sensor_width": 36.70,
            "sensor_height": 15.31,
            "image_width": 4448,
            "image_height": 1856,
            "codec": "ARRIRAW",
            "source": sources.get("Alexa Mini User Manual"),
        },
        {
            "camera": cameras.get("Alexa Mini LF")
            or Camera.objects.get("Alexa Mini LF"),
            "image_format": "3.8K LF",
            "image_aspect": "16:9",
            "format_name": "UHD",
            "sensor_width": 31.68,
            "sensor_height": 17.82,
            "image_width": 3840,
            "image_height": 2160,
            "codec": "ARRIRAW",
            "source": sources.get("Alexa Mini User Manual"),
        },
        {
            "camera": cameras.get("Alexa Mini LF")
            or Camera.objects.get("Alexa Mini LF"),
            "image_format": "2.8K LF",
            "image_aspect": "1:1",
            "sensor_width": 23.76,
            "sensor_height": 23.76,
            "image_width": 2880,
            "image_height": 2880,
            "codec": "ARRIRAW",
            "source": sources.get("Alexa Mini User Manual"),
        },
        {
            "camera": cameras.get("Alexa Mini LF")
            or Camera.objects.get("Alexa Mini LF"),
            "image_format": "3.4K",
            "image_aspect": "3.2",
            "format_name": "S35",
            "sensor_width": 28.25,
            "sensor_height": 18.16,
            "image_width": 3424,
            "image_height": 2202,
            "codec": "ARRIRAW",
            "source": sources.get("Alexa Mini User Manual"),
        },
        {
            "camera": cameras.get("Alexa Mini LF")
            or Camera.objects.get("Alexa Mini LF"),
            "image_format": "4.5K LF",
            "image_aspect": "3:2",
            "format_name": "Open Gate",
            "sensor_width": 36.70,
            "sensor_height": 25.54,
            "image_width": 4480,
            "image_height": 3096,
            "codec": "ProRes",
            "source": sources.get("Alexa Mini User Manual"),
            "make_notes": "This format adds 16px clip padding on left and right sides of frames. Sensor resolution is 4448x3096",
        },
        {
            "camera": cameras.get("Alexa Mini LF")
            or Camera.objects.get("Alexa Mini LF"),
            "image_format": "4.5K LF",
            "image_aspect": "2.39:1",
            "sensor_width": 36.70,
            "sensor_height": 15.31,
            "image_width": 4480,
            "image_height": 1856,
            "codec": "ProRes",
            "source": sources.get("Alexa Mini User Manual"),
            "make_notes": "This format adds 16px clip padding on left and right sides of frames. Sensor resolution is 4448x1856",
        },
        {
            "camera": cameras.get("Alexa Mini LF")
            or Camera.objects.get("Alexa Mini LF"),
            "image_format": "4.3K LF",
            "image_aspect": "16:9",
            "format_name": "UHD",
            "sensor_width": 35.64,
            "sensor_height": 20.05,
            "image_width": 3840,
            "image_height": 2160,
            "is_downsampled": True,
            "codec": "ProRes",
            "source": sources.get("Alexa Mini User Manual"),
            "notes": "This is a downsampled UHD format. Original sensor resolution was 4320×2430 pixels.",
        },
        {
            "camera": cameras.get("Alexa Mini LF")
            or Camera.objects.get("Alexa Mini LF"),
            "image_format": "4.3K LF",
            "image_aspect": "16:9",
            "format_name": "HD",
            "sensor_width": 35.64,
            "sensor_height": 20.05,
            "image_width": 1920,
            "image_height": 1080,
            "is_downsampled": True,
            "codec": "ProRes",
            "source": sources.get("Alexa Mini User Manual"),
            "notes": "This is a downsampled format. Original sensor resolution was 4320×2430 pixels.",
        },
        {
            "camera": cameras.get("Alexa Mini LF")
            or Camera.objects.get("Alexa Mini LF"),
            "image_format": "3.8K LF",
            "image_aspect": "16:9",
            "format_name": "UHD",
            "sensor_width": 31.68,
            "sensor_height": 17.82,
            "image_width": 3840,
            "image_height": 2160,
            "codec": "ProRes",
            "source": sources.get("Alexa Mini User Manual"),
        },
        {
            "camera": cameras.get("Alexa Mini LF")
            or Camera.objects.get("Alexa Mini LF"),
            "image_format": "3.8K LF",
            "image_aspect": "16:9",
            "format_name": "2K",
            "sensor_width": 31.68,
            "sensor_height": 17.82,
            "image_width": 2048,
            "image_height": 1152,
            "is_downsampled": True,
            "codec": "ProRes",
            "source": sources.get("Alexa Mini User Manual"),
            "notes": "This is a downsampled format. Original sensor resolution was 3840x2160 pixels.",
        },
        {
            "camera": cameras.get("Alexa Mini LF")
            or Camera.objects.get("Alexa Mini LF"),
            "image_format": "3.8K LF",
            "image_aspect": "16:9",
            "format_name": "HD",
            "sensor_width": 31.68,
            "sensor_height": 17.82,
            "image_width": 1920,
            "image_height": 1080,
            "is_downsampled": True,
            "codec": "ProRes",
            "source": sources.get("Alexa Mini User Manual"),
            "notes": "This is a downsampled format. Original sensor resolution was 3840x2160 pixels.",
        },
        {
            "camera": cameras.get("Alexa Mini LF")
            or Camera.objects.get("Alexa Mini LF"),
            "image_format": "2.8K LF",
            "image_aspect": "1:1",
            "sensor_width": 23.76,
            "sensor_height": 26.76,
            "image_width": 3072,
            "image_height": 3024,
            "codec": "ProRes",
            "source": sources.get("Alexa Mini User Manual"),
            "make_notes": "This format adds 96 px clip padding on left and right sides of frames and 72px padding on top and bottom. Sensor resolution is 2880x2880",
        },
        {
            "camera": cameras.get("Alexa Mini LF")
            or Camera.objects.get("Alexa Mini LF"),
            "image_format": "3.2K LF",
            "image_aspect": "16:9",
            "format_name": "S35",
            "sensor_width": 26.40,
            "sensor_height": 14.85,
            "image_width": 3200,
            "image_height": 1800,
            "codec": "ProRes",
            "source": sources.get("Alexa Mini User Manual"),
        },
        {
            "camera": cameras.get("Alexa Mini LF")
            or Camera.objects.get("Alexa Mini LF"),
            "image_format": "2.8K",
            "image_aspect": "4:3",
            "format_name": "S35",
            "sensor_width": 23.76,
            "sensor_height": 17.81,
            "image_width": 2880,
            "image_height": 2160,
            "codec": "ProRes",
            "source": sources.get("Alexa Mini User Manual"),
        },
        {
            "camera": cameras.get("Alexa Mini LF")
            or Camera.objects.get("Alexa Mini LF"),
            "image_format": "2.8K",
            "image_aspect": "4:3",
            "format_name": "HD",
            "sensor_width": 23.76,
            "sensor_height": 13.36,
            "image_width": 1920,
            "image_height": 1080,
            "is_downsampled": True,
            "codec": "ProRes",
            "source": sources.get("Alexa Mini User Manual"),
            "notes": "This is a downsampled format. Original sensor resolution was 2880x1620 pixels.",
        },
        {
            "camera": cameras.get("Alexa LF") or Camera.objects.get("Alexa LF"),
            "image_format": "4.5K",
            "image_aspect": "1.44:1",
            "format_name": "Open Gate",
            "sensor_width": 36.70,
            "sensor_height": 25.54,
            "image_width": 4448,
            "image_height": 3096,
            "codec": "ARRIRAW",
            "source": sources.get("Alexa LF Webpage"),
        },
        {
            "camera": cameras.get("Alexa LF") or Camera.objects.get("Alexa LF"),
            "image_format": "4.5K",
            "image_aspect": "1.44:1",
            "format_name": "Open Gate",
            "sensor_width": 36.70,
            "sensor_height": 25.54,
            "image_width": 4448,
            "image_height": 3096,
            "codec": "ProRes",
            "source": sources.get("Alexa LF Webpage"),
        },
        {
            "camera": cameras.get("Alexa LF") or Camera.objects.get("Alexa LF"),
            "image_format": "HD",
            "image_aspect": "16:9",
            "sensor_width": 31.68,
            "sensor_height": 17.82,
            "image_width": 1920,
            "image_height": 1080,
            "is_downsampled": True,
            "codec": "ProRes",
            "source": sources.get("Alexa LF Webpage"),
            "notes": "This is a downsampled format. Original sensor resolution was 3840x2160 pixels.",
        },
        {
            "camera": cameras.get("Alexa LF") or Camera.objects.get("Alexa LF"),
            "image_format": "2K",
            "image_aspect": "16:9",
            "sensor_width": 31.68,
            "sensor_height": 17.82,
            "image_width": 2048,
            "image_height": 1152,
            "is_downsampled": True,
            "codec": "ProRes",
            "source": sources.get("Alexa LF Webpage"),
            "notes": "This is a downsampled format. Original sensor resolution was 3840x2160 pixels.",
        },
        {
            "camera": cameras.get("Alexa LF") or Camera.objects.get("Alexa LF"),
            "image_format": "UHD",
            "image_aspect": "16:9",
            "sensor_width": 31.68,
            "sensor_height": 17.82,
            "image_width": 3840,
            "image_height": 2160,
            "codec": "ARRIRAW",
            "source": sources.get("Alexa LF Webpage"),
        },
        {
            "camera": cameras.get("Alexa LF") or Camera.objects.get("Alexa LF"),
            "image_format": "UHD",
            "image_aspect": "16:9",
            "sensor_width": 31.68,
            "sensor_height": 17.82,
            "image_width": 3840,
            "image_height": 2160,
            "codec": "ProRes",
            "source": sources.get("Alexa LF Webpage"),
        },
        {
            "camera": cameras.get("Alexa LF") or Camera.objects.get("Alexa LF"),
            "image_format": "4.5K",
            "image_aspect": "2.39:1",
            "sensor_width": 36.70,
            "sensor_height": 15.31,
            "image_width": 4448,
            "image_height": 1856,
            "codec": "ARRIRAW",
            "source": sources.get("Alexa LF Webpage"),
        },
        {
            "camera": cameras.get("Alexa LF") or Camera.objects.get("Alexa LF"),
            "image_format": "4.5K",
            "image_aspect": "2.39:1",
            "sensor_width": 36.70,
            "sensor_height": 15.31,
            "image_width": 4480,
            "image_height": 1856,
            "codec": "ProRes",
            "source": sources.get("Alexa LF Webpage"),
            "make_notes": "This format adds 16px clip padding on left and right sides of frames. Sensor resolution is 4448x1856",
        },
        {
            "camera": cameras.get("Alexa Amira") or Camera.objects.get("Alexa Amira"),
            "image_format": "HD",
            "image_aspect": "16:9",
            "format_name": "S16",
            "sensor_width": 13.2,
            "sensor_height": 7.43,
            "image_width": 1920,
            "image_height": 1080,
            "is_upscaled": True,
            "codec": "ProRes",
            "source": sources.get("Alexa Amira Webpage"),
            "notes": "This is an upscaled format. Original sensor resolution was 1600x900 pixels.",
        },
        {
            "camera": cameras.get("Alexa Amira") or Camera.objects.get("Alexa Amira"),
            "image_format": "HD",
            "image_aspect": "16:9",
            "sensor_width": 23.76,
            "sensor_height": 13.37,
            "image_width": 1920,
            "image_height": 1080,
            "is_downsampled": True,
            "codec": "ProRes",
            "source": sources.get("Alexa Amira Webpage"),
            "notes": "This is a downsampled format. Original sensor resolution was 2880x1620 pixels.",
        },
        {
            "camera": cameras.get("Alexa Amira") or Camera.objects.get("Alexa Amira"),
            "image_format": "2K",
            "image_aspect": "16:9",
            "sensor_width": 23.66,
            "sensor_height": 13.30,
            "image_width": 2048,
            "image_height": 1152,
            "is_downsampled": True,
            "codec": "ProRes",
            "source": sources.get("Alexa Amira Webpage"),
            "notes": "This is a downsampled format. Original sensor resolution was 2868x1612 pixels.",
        },
        {
            "camera": cameras.get("Alexa Amira") or Camera.objects.get("Alexa Amira"),
            "image_format": "3.2K",
            "image_aspect": "16:9",
            "sensor_width": 26.4,
            "sensor_height": 14.85,
            "image_width": 3200,
            "image_height": 1800,
            "codec": "ProRes",
            "source": sources.get("Alexa Amira Webpage"),
        },
        {
            "camera": cameras.get("Alexa Amira") or Camera.objects.get("Alexa Amira"),
            "image_format": "4K",
            "image_aspect": "16:9",
            "format_name": "UHD",
            "sensor_width": 26.40,
            "sensor_height": 14.85,
            "image_width": 3840,
            "image_height": 2160,
            "is_upscaled": True,
            "codec": "ProRes",
            "source": sources.get("Alexa Amira Webpage"),
            "notes": "This is an upscaled format. Original sensor resolution was 3200x1800 pixels.",
        },
        {
            "camera": cameras.get("Alexa Amira") or Camera.objects.get("Alexa Amira"),
            "image_format": "2.8K",
            "image_aspect": "16:9",
            "sensor_width": 23.76,
            "sensor_height": 13.37,
            "image_width": 2880,
            "image_height": 1620,
            "codec": "ARRIRAW",
            "source": sources.get("Alexa Amira Webpage"),
        },
        {
            "camera": cameras.get("Alexa SXT W") or Camera.objects.get("Alexa SXT W"),
            "image_format": "HD",
            "image_aspect": "16:9",
            "sensor_width": 23.76,
            "sensor_height": 13.37,
            "image_width": 1920,
            "image_height": 1080,
            "is_downsampled": True,
            "codec": "ProRes",
            "source": sources.get("Alexa SXT W Webpage"),
            "notes": "This is a downsampled format. Original sensor resolution was 2880x1620 pixels.",
        },
        {
            "camera": cameras.get("Alexa SXT W") or Camera.objects.get("Alexa SXT W"),
            "image_format": "2K",
            "image_aspect": "16:9",
            "sensor_width": 23.76,
            "sensor_height": 13.37,
            "image_width": 2048,
            "image_height": 1152,
            "codec": "ProRes",
            "source": sources.get("Alexa SXT W Webpage"),
            "notes": "This is a downsampled format. Original sensor resolution was 2880x1620 pixels.",
        },
        {
            "camera": cameras.get("Alexa SXT W") or Camera.objects.get("Alexa SXT W"),
            "image_format": "3.2K",
            "image_aspect": "16:9",
            "sensor_width": 26.40,
            "sensor_height": 14.85,
            "image_width": 3200,
            "image_height": 1800,
            "codec": "ProRes",
            "source": sources.get("Alexa SXT W Webpage"),
            "notes": "Container size may include additional padding (3200×1824).",
        },
        {
            "camera": cameras.get("Alexa SXT W") or Camera.objects.get("Alexa SXT W"),
            "image_format": "4K",
            "image_aspect": "16:9",
            "format_name": "UHD",
            "sensor_width": 26.40,
            "sensor_height": 14.85,
            "image_width": 3840,
            "image_height": 2160,
            "is_upscaled": True,
            "codec": "ProRes",
            "source": sources.get("Alexa SXT W Webpage"),
            "notes": "This is an upscaled format. Original sensor resolution was 3200x1800 pixels.",
        },
        {
            "camera": cameras.get("Alexa SXT W") or Camera.objects.get("Alexa SXT W"),
            "image_format": "2.8K",
            "image_aspect": "16:9",
            "sensor_width": 23.76,
            "sensor_height": 13.37,
            "image_width": 2880,
            "image_height": 1620,
            "codec": "ARRIRAW",
            "source": sources.get("Alexa SXT W Webpage"),
        },
        {
            "camera": cameras.get("Alexa SXT W") or Camera.objects.get("Alexa SXT W"),
            "image_format": "3.2K",
            "image_aspect": "16:9",
            "sensor_width": 26.14,
            "sensor_height": 14.70,
            "image_width": 3168,
            "image_height": 1782,
            "codec": "ARRIRAW",
            "source": sources.get("Alexa SXT W Webpage"),
        },
        {
            "camera": cameras.get("Alexa SXT W") or Camera.objects.get("Alexa SXT W"),
            "image_format": "2K",
            "image_aspect": "6:5",
            "format_name": "Anamorphic",
            "sensor_width": 21.12,
            "sensor_height": 17.70,
            "image_width": 2048,
            "image_height": 858,
            "is_downsampled": True,
            "is_anamorphic": True,
            "pixel_aspect": 2.0,
            "codec": "ProRes",
            "source": sources.get("Alexa SXT W Webpage"),
            "notes": "This is a downsampled format. Original sensor resolution was 2560x2146 pixels.",
        },
        {
            "camera": cameras.get("Alexa SXT W") or Camera.objects.get("Alexa SXT W"),
            "image_format": "4K Cine",
            "image_aspect": "6:5",
            "format_name": "Anamorphic",
            "sensor_width": 21.12,
            "sensor_height": 17.70,
            "image_width": 4096,
            "image_height": 1716,
            "is_upscaled": True,
            "is_anamorphic": True,
            "pixel_aspect": 2.0,
            "codec": "ProRes",
            "source": sources.get("Alexa SXT W Webpage"),
            "notes": "This is an upscaled format. Original sensor resolution was 2560x2146 pixels.",
        },
        {
            "camera": cameras.get("Alexa SXT W") or Camera.objects.get("Alexa SXT W"),
            "image_format": "2.6K",
            "image_aspect": "6:5",
            "sensor_width": 21.38,
            "sensor_height": 17.82,
            "image_width": 2578,
            "image_height": 2160,
            "codec": "ARRIRAW",
            "source": sources.get("Alexa SXT W Webpage"),
        },
        {
            "camera": cameras.get("Alexa SXT W") or Camera.objects.get("Alexa SXT W"),
            "image_format": "2.8K",
            "image_aspect": "4:3",
            "sensor_width": 23.76,
            "sensor_height": 17.82,
            "image_width": 2880,
            "image_height": 2160,
            "codec": "ProRes",
            "source": sources.get("Alexa SXT W Webpage"),
        },
        {
            "camera": cameras.get("Alexa SXT W") or Camera.objects.get("Alexa SXT W"),
            "image_format": "2.8K",
            "image_aspect": "4:3",
            "sensor_width": 23.76,
            "sensor_height": 17.82,
            "image_width": 2880,
            "image_height": 2160,
            "codec": "ARRIRAW",
            "source": sources.get("Alexa SXT W Webpage"),
        },
        {
            "camera": cameras.get("Alexa SXT W") or Camera.objects.get("Alexa SXT W"),
            "image_format": "3.4K",
            "format_name": "Open Gate",
            "sensor_width": 28.25,
            "sensor_height": 18.17,
            "image_width": 3424,
            "image_height": 2202,
            "codec": "ProRes",
            "source": sources.get("Alexa SXT W Webpage"),
        },
        {
            "camera": cameras.get("Alexa SXT W") or Camera.objects.get("Alexa SXT W"),
            "image_format": "4K Cine",
            "format_name": "Open Gate",
            "sensor_width": 28.17,
            "sensor_height": 18.13,
            "image_width": 4096,
            "image_height": 2636,
            "is_upscaled": True,
            "codec": "ProRes",
            "source": sources.get("Alexa SXT W Webpage"),
            "notes": "This is an upscaled format. Original sensor resolution was 3414x2198 pixels.",
        },
        {
            "camera": cameras.get("Alexa SXT W") or Camera.objects.get("Alexa SXT W"),
            "image_format": "3.4K",
            "format_name": "Open Gate",
            "sensor_width": 28.25,
            "sensor_height": 18.17,
            "image_width": 3424,
            "image_height": 2202,
            "codec": "ARRIRAW",
            "source": sources.get("Alexa SXT W Webpage"),
        },
        {
            "camera": cameras.get("Alexa Mini") or Camera.objects.get("Alexa Mini"),
            "image_format": "2.8K",
            "image_aspect": "16:9",
            "format_name": "HD",
            "sensor_width": 23.76,
            "sensor_height": 13.37,
            "image_width": 2880,
            "image_height": 1620,
            "codec": "ARRIRAW",
            "source": sources.get("Alexa Mini Recording Area Document"),
        },
        {
            "camera": cameras.get("Alexa Mini") or Camera.objects.get("Alexa Mini"),
            "image_format": "2.8K",
            "image_aspect": "16:9",
            "format_name": "HD",
            "sensor_width": 23.76,
            "sensor_height": 13.37,
            "image_width": 1920,
            "image_height": 1080,
            "is_downsampled": True,
            "codec": "ProRes",
            "source": sources.get("Alexa Mini Recording Area Document"),
            "make_notes": "Downscaled from 2880x1620",
        },
        {
            "camera": cameras.get("Alexa Mini") or Camera.objects.get("Alexa Mini"),
            "image_format": "2K",
            "image_aspect": "16:9",
            "sensor_width": 23.66,
            "sensor_height": 13.30,
            "image_width": 2048,
            "image_height": 1152,
            "is_downsampled": True,
            "codec": "ProRes",
            "source": sources.get("Alexa Mini Recording Area Document"),
            "make_notes": "Downscaled from 2868x1612",
        },
        {
            "camera": cameras.get("Alexa Mini") or Camera.objects.get("Alexa Mini"),
            "image_format": "3.2K",
            "image_aspect": "16:9",
            "sensor_width": 26.40,
            "sensor_height": 14.85,
            "image_width": 3200,
            "image_height": 1800,
            "codec": "ProRes",
            "source": sources.get("Alexa Mini Recording Area Document"),
        },
        {
            "camera": cameras.get("Alexa Mini") or Camera.objects.get("Alexa Mini"),
            "image_format": "4K",
            "image_aspect": "16:9",
            "format_name": "UHD",
            "sensor_width": 26.40,
            "sensor_height": 14.85,
            "image_width": 3840,
            "image_height": 2160,
            "codec": "ProRes",
            "is_upscaled": True,
            "source": sources.get("Alexa Mini Recording Area Document"),
            "make_notes": "Upscaled from the 3.2K format which is 3200x1800",
        },
        {
            "camera": cameras.get("Alexa Mini") or Camera.objects.get("Alexa Mini"),
            "image_format": "HD",
            "image_aspect": "16:9",
            "format_name": "Ana.",
            "sensor_width": 15.84,
            "sensor_height": 17.82,
            "image_width": 1920,
            "image_height": 1080,
            "is_anamorphic": True,
            "is_desqueezed": True,
            "pixel_aspect": 2.0,
            "codec": "ProRes",
            "source": sources.get("Alexa Mini Recording Area Document"),
            "make_notes": "Applies a 2.0 anamorphic desqueeze to the image and records images in 1920x1080 resolution from 1920x2160",
        },
        {
            "camera": cameras.get("Alexa Mini") or Camera.objects.get("Alexa Mini"),
            "image_format": "2K",
            "image_aspect": "2.39:1",
            "format_name": "Ana.",
            "sensor_width": 21.12,
            "sensor_height": 17.70,
            "image_width": 2048,
            "image_height": 858,
            "is_anamorphic": True,
            "pixel_aspect": 2.0,
            "is_desqueezed": True,
            "codec": "ProRes",
            "source": sources.get("Alexa Mini Recording Area Document"),
            "make_notes": "Applies a 2.0 anamorphic desqueeze to the image and records images in 2048x858 resolution from 2560x2145",
        },
        {
            "camera": cameras.get("Alexa Mini") or Camera.objects.get("Alexa Mini"),
            "image_format": "2.8K",
            "image_aspect": "4:3",
            "sensor_width": 23.76,
            "sensor_height": 17.82,
            "image_width": 2944,
            "image_height": 2160,
            "is_upscaled": True,
            "codec": "ProRes",
            "source": sources.get("Alexa Mini Recording Area Document"),
            "make_notes": "Upscaled from 2880x2160",
        },
        {
            "camera": cameras.get("Alexa Mini") or Camera.objects.get("Alexa Mini"),
            "image_format": "HD",
            "image_aspect": "16:9",
            "format_name": "Ana.",
            "sensor_width": 15.84,
            "sensor_height": 17.82,
            "image_width": 1920,
            "image_height": 1080,
            "is_anamorphic": True,
            "pixel_aspect": 2.0,
            "is_desqueezed": True,
            "codec": "ARRIRAW",
            "source": sources.get("Alexa Mini Recording Area Document"),
            "make_notes": "Applies a 2.0 anamorphic desqueeze to the image and records images in 1920x1080 resolution from 1920x2160",
        },
        {
            "camera": cameras.get("Alexa Mini") or Camera.objects.get("Alexa Mini"),
            "image_format": "2K",
            "image_aspect": "2.39:1",
            "format_name": "Ana.",
            "sensor_width": 21.12,
            "sensor_height": 17.70,
            "image_width": 2048,
            "image_height": 858,
            "is_anamorphic": True,
            "is_desqueezed": True,
            "pixel_aspect": 2.0,
            "codec": "ARRIRAW",
            "source": sources.get("Alexa Mini Recording Area Document"),
            "make_notes": "Applies a 2.0 anamorphic desqueeze to the image and records images in 2048x858 resolution from 2560x2145",
        },
        {
            "camera": cameras.get("Alexa Mini") or Camera.objects.get("Alexa Mini"),
            "image_format": "2.8K",
            "image_aspect": "4:3",
            "sensor_width": 23.76,
            "sensor_height": 17.82,
            "image_width": 2880,
            "image_height": 2160,
            "codec": "ARRIRAW",
            "source": sources.get("Alexa Mini Recording Area Document"),
        },
        {
            "camera": cameras.get("Alexa Mini") or Camera.objects.get("Alexa Mini"),
            "image_format": "2.8K",
            "image_aspect": "4:3",
            "sensor_width": 23.76,
            "sensor_height": 17.82,
            "image_width": 2944,
            "image_height": 2160,
            "is_downsampled": True,
            "codec": "ProRes",
            "source": sources.get("Alexa Mini Recording Area Document"),
            "make_notes": "Downsampled from Open Gate",
        },
        {
            "camera": cameras.get("Alexa Mini") or Camera.objects.get("Alexa Mini"),
            "image_format": "3.4K",
            "image_aspect": "1.55:1",
            "format_name": "Open Gate",
            "sensor_width": 28.25,
            "sensor_height": 18.17,
            "image_width": 3424,
            "image_height": 2202,
            "codec": "ARRIRAW",
            "source": sources.get("Alexa Mini Recording Area Document"),
        },
        {
            "camera": cameras.get("Alexa Mini") or Camera.objects.get("Alexa Mini"),
            "image_format": "2.8K",
            "image_aspect": "4:3",
            "format_name": "OG 3.4",
            "sensor_width": 28.25,
            "sensor_height": 18.17,
            "image_width": 3424,
            "image_height": 2202,
            "codec": "ARRIRAW",
            "source": sources.get("Alexa Mini Recording Area Document"),
        },
        {
            "camera": cameras.get("Alexa Mini") or Camera.objects.get("Alexa Mini"),
            "image_format": "3.4K",
            "image_aspect": "16:9",
            "format_name": "HD Ana.",
            "sensor_width": 28.25,
            "sensor_height": 18.17,
            "image_width": 3424,
            "image_height": 2202,
            "is_anamorphic": True,
            "codec": "ARRIRAW",
            "source": sources.get("Alexa Mini Recording Area Document"),
        },
        {
            "camera": cameras.get("Alexa Mini") or Camera.objects.get("Alexa Mini"),
            "image_format": "3.4K",
            "image_aspect": "2.39:1",
            "format_name": "2K Ana.",
            "sensor_width": 28.25,
            "sensor_height": 18.17,
            "image_width": 3424,
            "image_height": 2202,
            "is_anamorphic": True,
            "codec": "ARRIRAW",
            "source": sources.get("Alexa Mini Recording Area Document"),
        },
        {
            "camera": cameras.get("Alexa Mini") or Camera.objects.get("Alexa Mini"),
            "image_format": "HD",
            "image_aspect": "16:9",
            "format_name": "S16",
            "sensor_width": 13.20,
            "sensor_height": 7.43,
            "image_width": 1920,
            "image_height": 1080,
            "codec": "ProRes",
            "source": sources.get("Alexa Mini Recording Area Document"),
            "make_notes": "Records images in 1920x1080 resolution. Uses a 1600x900 sensor center crop and scales it to 1920x1080.",
        },
        {
            "camera": cameras.get("KOMODO") or Camera.objects.get("KOMODO"),
            "image_format": "6K",
            "image_aspect": "17:9",
            "sensor_width": 27.03,
            "sensor_height": 14.26,
            "image_width": 6144,
            "image_height": 3240,
            "codec": "R3D",
            "source": sources.get("KOMODO Operation Guide"),
        },
        {
            "camera": cameras.get("KOMODO") or Camera.objects.get("KOMODO"),
            "image_format": "6K",
            "image_aspect": "2:1",
            "sensor_width": 27.03,
            "sensor_height": 13.52,
            "image_width": 6144,
            "image_height": 3072,
            "codec": "R3D",
            "source": sources.get("KOMODO Operation Guide"),
        },
        {
            "camera": cameras.get("KOMODO") or Camera.objects.get("KOMODO"),
            "image_format": "6K",
            "image_aspect": "2.4:1",
            "sensor_width": 27.03,
            "sensor_height": 11.40,
            "image_width": 6144,
            "image_height": 2592,
            "codec": "R3D",
            "source": sources.get("KOMODO Operation Guide"),
            "notes": "There is a discrapency in the documentation the height is either 2592 or 2574",
        },
        {
            "camera": cameras.get("KOMODO") or Camera.objects.get("KOMODO"),
            "image_format": "6K",
            "image_aspect": "16:9",
            "sensor_width": 25.34,
            "sensor_height": 14.26,
            "image_width": 5760,
            "image_height": 3240,
            "codec": "R3D",
            "source": sources.get("KOMODO Operation Guide"),
        },
        {
            "camera": cameras.get("KOMODO") or Camera.objects.get("KOMODO"),
            "image_format": "6K",
            "image_aspect": "1:1",
            "sensor_width": 14.26,
            "sensor_height": 14.26,
            "image_width": 3240,
            "image_height": 3240,
            "codec": "R3D",
            "source": sources.get("KOMODO Operation Guide"),
        },
        {
            "camera": cameras.get("KOMODO") or Camera.objects.get("KOMODO"),
            "image_format": "6K",
            "image_aspect": "4:3",
            "sensor_width": 19.01,
            "sensor_height": 14.26,
            "image_width": 4320,
            "image_height": 3240,
            "is_anamorphic": True,
            "pixel_aspect": 2.0,
            "codec": "R3D",
            "source": sources.get("KOMODO Operation Guide"),
        },
        {
            "camera": cameras.get("KOMODO") or Camera.objects.get("KOMODO"),
            "image_format": "6K",
            "image_aspect": "6:5",
            "sensor_width": 17.11,
            "sensor_height": 14.26,
            "image_width": 3888,
            "image_height": 3240,
            "is_anamorphic": True,
            "pixel_aspect": 2.0,
            "codec": "R3D",
            "source": sources.get("KOMODO Operation Guide"),
        },
        {
            "camera": cameras.get("KOMODO") or Camera.objects.get("KOMODO"),
            "image_format": "6K",
            "image_aspect": "1:1",
            "sensor_width": 14.26,
            "sensor_height": 14.26,
            "image_width": 3240,
            "image_height": 3240,
            "is_anamorphic": True,
            "pixel_aspect": 2.0,
            "codec": "R3D",
            "source": sources.get("KOMODO Operation Guide"),
        },
        {
            "camera": cameras.get("KOMODO") or Camera.objects.get("KOMODO"),
            "image_format": "6K",
            "image_aspect": "3:2",
            "sensor_width": 21.38,
            "sensor_height": 14.26,
            "image_width": 4860,
            "image_height": 3240,
            "is_anamorphic": True,
            "pixel_aspect": 1.8,
            "codec": "R3D",
            "source": sources.get("KOMODO Operation Guide"),
        },
        {
            "camera": cameras.get("KOMODO") or Camera.objects.get("KOMODO"),
            "image_format": "6K",
            "image_aspect": "4:3",
            "sensor_width": 19.01,
            "sensor_height": 14.26,
            "image_width": 4320,
            "image_height": 3240,
            "is_anamorphic": True,
            "pixel_aspect": 1.8,
            "codec": "R3D",
            "source": sources.get("KOMODO Operation Guide"),
        },
        {
            "camera": cameras.get("KOMODO") or Camera.objects.get("KOMODO"),
            "image_format": "6K",
            "image_aspect": "3:2",
            "sensor_width": 21.38,
            "sensor_height": 14.26,
            "image_width": 4860,
            "image_height": 3240,
            "is_anamorphic": True,
            "pixel_aspect": 1.6,
            "codec": "R3D",
            "source": sources.get("KOMODO Operation Guide"),
        },
        {
            "camera": cameras.get("KOMODO") or Camera.objects.get("KOMODO"),
            "image_format": "6K",
            "image_aspect": "16:9",
            "sensor_width": 25.34,
            "sensor_height": 14.26,
            "image_width": 5760,
            "image_height": 3240,
            "is_anamorphic": True,
            "pixel_aspect": 1.5,
            "codec": "R3D",
            "source": sources.get("KOMODO Operation Guide"),
        },
        {
            "camera": cameras.get("KOMODO") or Camera.objects.get("KOMODO"),
            "image_format": "6K",
            "image_aspect": "17:9",
            "sensor_width": 27.03,
            "sensor_height": 14.26,
            "image_width": 6144,
            "image_height": 3240,
            "is_anamorphic": True,
            "pixel_aspect": 1.3,
            "codec": "R3D",
            "source": sources.get("KOMODO Operation Guide"),
        },
        {
            "camera": cameras.get("KOMODO") or Camera.objects.get("KOMODO"),
            "image_format": "6K",
            "image_aspect": "17:9",
            "sensor_width": 27.03,
            "sensor_height": 14.26,
            "image_width": 6144,
            "image_height": 3240,
            "is_anamorphic": True,
            "pixel_aspect": 1.25,
            "codec": "R3D",
            "source": sources.get("KOMODO Operation Guide"),
        },
        {
            "camera": cameras.get("KOMODO") or Camera.objects.get("KOMODO"),
            "image_format": "5K",
            "image_aspect": "17:9",
            "sensor_width": 22.53,
            "sensor_height": 11.88,
            "image_width": 5120,
            "image_height": 2700,
            "codec": "R3D",
            "source": sources.get("KOMODO Operation Guide"),
        },
        {
            "camera": cameras.get("KOMODO") or Camera.objects.get("KOMODO"),
            "image_format": "4K",
            "image_aspect": "17:9",
            "sensor_width": 18.02,
            "sensor_height": 9.50,
            "image_width": 4096,
            "image_height": 2160,
            "codec": "R3D",
            "source": sources.get("KOMODO Operation Guide"),
        },
        {
            "camera": cameras.get("KOMODO") or Camera.objects.get("KOMODO"),
            "image_format": "4K",
            "image_aspect": "16:9",
            "sensor_width": 16.90,
            "sensor_height": 9.50,
            "image_width": 3840,
            "image_height": 2160,
            "codec": "R3D",
            "source": sources.get("KOMODO Operation Guide"),
        },
        {
            "camera": cameras.get("KOMODO") or Camera.objects.get("KOMODO"),
            "image_format": "2K",
            "image_aspect": "17:9",
            "sensor_width": 9.01,
            "sensor_height": 4.75,
            "image_width": 2048,
            "image_height": 1080,
            "codec": "R3D",
            "source": sources.get("KOMODO Operation Guide"),
        },
        {
            "camera": cameras.get("KOMODO-X") or Camera.objects.get("KOMODO-X"),
            "image_format": "6K",
            "image_aspect": "17:9",
            "sensor_width": 27.03,
            "sensor_height": 14.26,
            "image_width": 6144,
            "image_height": 3240,
            "codec": "R3D",
            "source": sources.get("KOMODO-X Operation Guide"),
        },
        {
            "camera": cameras.get("KOMODO-X") or Camera.objects.get("KOMODO-X"),
            "image_format": "6K",
            "image_aspect": "2:1",
            "sensor_width": 27.03,
            "sensor_height": 13.52,
            "image_width": 6144,
            "image_height": 3072,
            "codec": "R3D",
            "source": sources.get("KOMODO-X Operation Guide"),
        },
        {
            "camera": cameras.get("KOMODO-X") or Camera.objects.get("KOMODO-X"),
            "image_format": "6K",
            "image_aspect": "2.4:1",
            "sensor_width": 27.03,
            "sensor_height": 11.40,
            "image_width": 6144,
            "image_height": 2592,
            "codec": "R3D",
            "source": sources.get("KOMODO-X Operation Guide"),
            "notes": "There is a discrapency in the documentation the height is either 2592 or 2574",
        },
        {
            "camera": cameras.get("KOMODO-X") or Camera.objects.get("KOMODO-X"),
            "image_format": "6K",
            "image_aspect": "16:9",
            "sensor_width": 25.34,
            "sensor_height": 14.26,
            "image_width": 5760,
            "image_height": 3240,
            "codec": "R3D",
            "source": sources.get("KOMODO-X Operation Guide"),
        },
        {
            "camera": cameras.get("KOMODO-X") or Camera.objects.get("KOMODO-X"),
            "image_format": "6K",
            "image_aspect": "1:1",
            "sensor_width": 14.26,
            "sensor_height": 14.26,
            "image_width": 3240,
            "image_height": 3240,
            "codec": "R3D",
            "source": sources.get("KOMODO-X Operation Guide"),
        },
        {
            "camera": cameras.get("KOMODO-X") or Camera.objects.get("KOMODO-X"),
            "image_format": "6K",
            "image_aspect": "4:3",
            "sensor_width": 19.01,
            "sensor_height": 14.26,
            "image_width": 4320,
            "image_height": 3240,
            "is_anamorphic": True,
            "pixel_aspect": 2.0,
            "codec": "R3D",
            "source": sources.get("KOMODO-X Operation Guide"),
        },
        {
            "camera": cameras.get("KOMODO-X") or Camera.objects.get("KOMODO-X"),
            "image_format": "6K",
            "image_aspect": "6:5",
            "sensor_width": 17.11,
            "sensor_height": 14.26,
            "image_width": 3888,
            "image_height": 3240,
            "is_anamorphic": True,
            "pixel_aspect": 2.0,
            "codec": "R3D",
            "source": sources.get("KOMODO-X Operation Guide"),
        },
        {
            "camera": cameras.get("KOMODO-X") or Camera.objects.get("KOMODO-X"),
            "image_format": "6K",
            "image_aspect": "1:1",
            "sensor_width": 14.26,
            "sensor_height": 14.26,
            "image_width": 3240,
            "image_height": 3240,
            "is_anamorphic": True,
            "pixel_aspect": 2.0,
            "codec": "R3D",
            "source": sources.get("KOMODO-X Operation Guide"),
        },
        {
            "camera": cameras.get("KOMODO-X") or Camera.objects.get("KOMODO-X"),
            "image_format": "6K",
            "image_aspect": "3:2",
            "sensor_width": 21.38,
            "sensor_height": 14.26,
            "image_width": 4860,
            "image_height": 3240,
            "is_anamorphic": True,
            "pixel_aspect": 1.8,
            "codec": "R3D",
            "source": sources.get("KOMODO-X Operation Guide"),
        },
        {
            "camera": cameras.get("KOMODO-X") or Camera.objects.get("KOMODO-X"),
            "image_format": "6K",
            "image_aspect": "4:3",
            "sensor_width": 19.01,
            "sensor_height": 14.26,
            "image_width": 4320,
            "image_height": 3240,
            "is_anamorphic": True,
            "pixel_aspect": 1.8,
            "codec": "R3D",
            "source": sources.get("KOMODO-X Operation Guide"),
        },
        {
            "camera": cameras.get("KOMODO-X") or Camera.objects.get("KOMODO-X"),
            "image_format": "6K",
            "image_aspect": "3:2",
            "sensor_width": 21.38,
            "sensor_height": 14.26,
            "image_width": 4860,
            "image_height": 3240,
            "is_anamorphic": True,
            "pixel_aspect": 1.6,
            "codec": "R3D",
            "source": sources.get("KOMODO-X Operation Guide"),
        },
        {
            "camera": cameras.get("KOMODO-X") or Camera.objects.get("KOMODO-X"),
            "image_format": "6K",
            "image_aspect": "16:9",
            "sensor_width": 25.34,
            "sensor_height": 14.26,
            "image_width": 5760,
            "image_height": 3240,
            "is_anamorphic": True,
            "pixel_aspect": 1.5,
            "codec": "R3D",
            "source": sources.get("KOMODO-X Operation Guide"),
        },
        {
            "camera": cameras.get("KOMODO-X") or Camera.objects.get("KOMODO-X"),
            "image_format": "6K",
            "image_aspect": "17:9",
            "sensor_width": 27.03,
            "sensor_height": 14.26,
            "image_width": 6144,
            "image_height": 3240,
            "is_anamorphic": True,
            "pixel_aspect": 1.3,
            "codec": "R3D",
            "source": sources.get("KOMODO-X Operation Guide"),
        },
        {
            "camera": cameras.get("KOMODO-X") or Camera.objects.get("KOMODO-X"),
            "image_format": "6K",
            "image_aspect": "17:9",
            "sensor_width": 27.03,
            "sensor_height": 14.26,
            "image_width": 6144,
            "image_height": 3240,
            "is_anamorphic": True,
            "pixel_aspect": 1.25,
            "codec": "R3D",
            "source": sources.get("KOMODO-X Operation Guide"),
        },
        {
            "camera": cameras.get("KOMODO-X") or Camera.objects.get("KOMODO-X"),
            "image_format": "5K",
            "image_aspect": "17:9",
            "sensor_width": 22.53,
            "sensor_height": 11.88,
            "image_width": 5120,
            "image_height": 2700,
            "codec": "R3D",
            "source": sources.get("KOMODO-X Operation Guide"),
        },
        {
            "camera": cameras.get("KOMODO-X") or Camera.objects.get("KOMODO-X"),
            "image_format": "5K",
            "image_aspect": "16:9",
            "sensor_width": 21.12,
            "sensor_height": 11.88,
            "image_width": 4800,
            "image_height": 2700,
            "codec": "R3D",
            "source": sources.get("KOMODO-X Operation Guide"),
        },
        {
            "camera": cameras.get("KOMODO-X") or Camera.objects.get("KOMODO-X"),
            "image_format": "4K",
            "image_aspect": "17:9",
            "sensor_width": 18.02,
            "sensor_height": 9.50,
            "image_width": 4096,
            "image_height": 2160,
            "codec": "R3D",
            "source": sources.get("KOMODO-X Operation Guide"),
        },
        {
            "camera": cameras.get("KOMODO-X") or Camera.objects.get("KOMODO-X"),
            "image_format": "4K",
            "image_aspect": "16:9",
            "sensor_width": 16.90,
            "sensor_height": 9.50,
            "image_width": 3840,
            "image_height": 2160,
            "codec": "R3D",
            "source": sources.get("KOMODO-X Operation Guide"),
        },
        {
            "camera": cameras.get("KOMODO-X") or Camera.objects.get("KOMODO-X"),
            "image_format": "2K",
            "image_aspect": "17:9",
            "sensor_width": 9.01,
            "sensor_height": 4.75,
            "image_width": 2048,
            "image_height": 1080,
            "codec": "R3D",
            "source": sources.get("KOMODO-X Operation Guide"),
        },
    ]

    created_formats = {}
    for fmt in formats:
        format_record, new = Format.objects.get_or_create(**fmt)
        created_formats[format_record.id] = format_record
        logger.info(
            f"{'Created' if new else 'Found'} format: {format_record.image_format} {format_record.image_aspect} {format_record.format_name} {format_record.codec} {format_record.id}"
        )


def seed_db():
    makes = seed_makes()
    cameras = seed_cameras(makes)
    sources = seed_sources()
    formats = seed_formats(cameras, sources)
